---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 0TEX0.
--- DateTime: 12/08/2023 17:35
---

Lang = Lang or {}
Lang["en"] = {
	["title"] = "Music",
	["subtitle"] = "Music player",
	["title_info"] = "Music Menu",
	["play"] = "Play music",
	["pause"] = "Pause",
	["stop"] = "Stop",
	["volume"] = "Volume",
	["time_stamp"] = "Time stamp",
	["input"] = "Enter the url | https://www.youtube.com/watch?v=...",
	["press_to_open_menu"] = "Press ~INPUT_PICKUP~ to open the music menu",
	["music_time"] = "Music time",
	["music_paused"] = "~y~Paused~s~",
	["music_playing"] = "~g~Playing~s~",
	["no_music_playing"] = "~r~Not Playing~s~",
	["no_music"] = "~r~No music~s~"
}