---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 0TEX0.
--- DateTime: 12/08/2023 17:35
---

Lang = Lang or {}
Lang["fr"] = {
	["title"] = "Musique",
	["subtitle"] = "Lecteur de musique",
	["title_info"] = "Menu Musique",
	["play"] = "Lire la musique",
	["pause"] = "Pause",
	["stop"] = "Arrêter",
	["volume"] = "Volume",
	["time_stamp"] = "Horodatage",
	["input"] = "Entrez l'URL | https://www.youtube.com/watch?v=...",
	["press_to_open_menu"] = "Appuyez sur ~INPUT_PICKUP~ pour ouvrir le menu musique",
	["music_time"] = "Durée de la musique",
	["music_paused"] = "~y~Musique en pause~s~",
	["music_playing"] = "~g~En cours de lecture~s~",
	["no_music_playing"] = "~r~Aucune lecture en cours~s~",
	["no_music"] = "~r~Aucune musique~s~"
}